import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import "./globals.css";
// import NavBarDash from "@/components/User/NavBarDash";
// import SideBar from "@/components/User/SideBar";
import NavBarStores from "./_components/NavBarStores";
import StoreProvider from "../StoreProvider";

// const roboto = Roboto({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Matjarify",
    template: "Matjarify | %s",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="font-universal-sans relative flex min-h-screen">
        <div className="top-0 fixed w-full z-50 ">
            {/* <NavBarStores /> */}
        </div>
          <div className=" bg-secondary h-full w-full">{children}</div>
      </div>
  );
}
