import type { Metadata } from "next";
import { Lato } from "next/font/google";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footers/Footers";

const lato = Lato({
  weight: ["400", "700", "100", "300", "900"],
  style: ["normal"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full relative">
      <div className="top-0 z-50 absolute w-full">
        <NavBar />
      </div>
      {children}
      <div>
        <Footer />
      </div>
    </div>
  );
}
