import type { Metadata } from "next";
import DeliveryDetails from "./_components/Body/SectoinEnd/DeliveryDetails/DeliveryDetails";
import Footers from "./_components/Footers/Footers";
import NavBar from "./_components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="min-h-screen">
        <NavBar />
        {children}
        <DeliveryDetails />
      </div>
      <Footers />
    </>
  );
}
