import type { Metadata } from "next";
import FilterBar from "./_components/SearchBar/FilterBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full relative">
      <div className="w-full">
        <FilterBar />
      </div>
      {children}
    </div>
  );
}
